
# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.9

# Install the codecov pip dependency
install:
  - pipenv install

# Run the unit test
script:
  - pytest .
